# configs/config_foodseg.yaml
experiment_name: "unet_foodseg_advanced_A"

dataset:
  name: "EduardoPacheco/FoodSeg103"
  image_size: 512
  batch_size: 8
  num_workers: 2
  reflect_threshold: 220
  compute_reflect: true

training:
  epochs: 60
  lr: 1e-4
  loss_mode: "advanced"

  alpha: 0.6          # Dice
  beta: 0.4           # Consistency

  lambda_edge: 0.8
  lambda_reflect: 0.2
  sigma_edge: 5.0

  save_interval: 10

logging:
  use_tensorboard: true
  log_dir: "experiments/logs"
  checkpoint_dir: "experiments/checkpoints"