dataset:
  image_size: 256
  batch_size: 8
  num_workers: 2

training:
  model_type: simple_cnn
  epochs: 60
  lr: 0.0001
  loss_mode: baseline   # ðŸ‘ˆ baseline loss

  # Disable advanced loss
  alpha: 0.0
  beta: 0.0
  lambda_edge: 0.0
  lambda_reflect: 0.0
  sigma_edge: 0.0

logging:
  use_tensorboard: true
  log_dir: runs/cnn_baseline
  checkpoint_dir: checkpoints/cnn_baseline