dataset:
  image_size: 256
  batch_size: 8
  num_workers: 2

training:
  model_type: unet
  epochs: 60
  lr: 0.0001
  loss_mode: vanilla   # ðŸ‘ˆ vanilla UNet loss

  # Use CE + Dice
  alpha: 0.5
  beta: 0.0

  # Turn off advanced components
  lambda_edge: 0.0
  lambda_reflect: 0.0
  sigma_edge: 0.0

logging:
  use_tensorboard: true
  log_dir: runs/unet
  checkpoint_dir: checkpoints/unet